### ISSUE TITLE
Great Work. Add support for Demucs?

### ISSUE THREAD

**Issue by cjhines7** [MrPatben8/AutoStemReloaded#1]
Thanks for this excellent software. IMO, Spleeter doesn't do as good a job as Demucs. Any chance of adding this?

**Comment by MrPatben8** [comment]
Thanks! I actually never heard of Demucs, but I'll take a look at it

**Comment by cjhines7** [comment]
https://github.com/facebookresearch/demucs

It's slower, but the quality is worth it

**Comment by MrPatben8** [comment]
Alright, thanks for the tip!

**Comment by MrPatben8** [comment]
Does it also do 4 stem separation? Or only vocals and instrumental separation?

**Comment by cjhines7** [comment]
Yes it does.

**Comment by MrPatben8** [comment]
Awesome! I'll see what I can do and I'll notify you if the change is made

**Comment by MrPatben8** [comment]
@cjhines7 Support for Demucs has been added! Thank you for your suggestion. It was actually quite easy to implement, basically a drop-in replacement.
I did some tests and while MUCH slower than Spleeter, the fidelity of the separation is worth it. The separation model can be changed in the output settings page.

**Comment by cjhines7** [comment]
That was fast. Thanks for this. Gonna try it out this weekend

**Comment by MrPatben8** [comment]
I did some testing. If you have an Nvidia GPU then I strongly suggest you do the GPU accelerated install of Demucs. It's even faster that Spleeter, crazy fast.
